# Instituto Tecnológico de Monterrey
# Ciencia y analítica de datos
# A01793599 Gustavo René Ramos Ojeda

# Módulo 5 - Quiz on 2D Numpy Array

In [1]:
# A01793599 - GUSRAMOS -- CONVERTIR A ARREGLOS NUMPY

import numpy as np

a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

arrayA = np.array(a)

print( arrayA )

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [2]:
# A01793599 - GUSRAMOS -- CALCULAR TAMAÑO   

print( arrayA.size )

12


In [4]:
# A01793599 - GUSRAMOS -- ACCEDER FIRST ROW AND FIRST AND SECOND COLUMNS

print( arrayA[0][ 0:2] )

[1 2]


In [6]:
# A01793599 - GUSRAMOS -- multiplicación de matriz


arrayB = np.array([[0, 1], [1, 0], [1, 1], [-1, 0]])

print( np.dot( arrayA, arrayB ) )

[[ 1  4]
 [ 5 12]
 [ 9 20]]
